server:
  port: 8088

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: true
    hibernate:
      ddl-auto: none